#!/usr/bin/env bash
# Copies the canonical docs/ folder into each package so the published tarballs
# ship with the docs alongside the README. The copies are .gitignored and
# regenerated by package-level prepack / pre-build hooks.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/docs"

if [ ! -d "$SRC" ]; then
  echo "error: $SRC does not exist" >&2
  exit 1
fi

copy_docs() {
  local dst="$1"
  rm -rf "$dst"
  mkdir -p "$dst"
  # Copy markdown only — Jekyll config/Gemfile aren't useful inside packages.
  for f in "$SRC"/*.md; do
    [ -e "$f" ] || continue
    cp "$f" "$dst/"
  done
  echo "synced docs -> ${dst#$REPO_ROOT/}"
}

# Sibling-of-README copy: lets relative `./docs/...` links resolve in repo
# checkouts and inside the published package tarballs (npm + Python sdist).
copy_docs "$REPO_ROOT/packages/javascript/docs"
copy_docs "$REPO_ROOT/packages/python/docs"

# Inside-package copy: ensures the docs ship inside the Python wheel, so
# agents inspecting an installed `site-packages/cachetta/` see them too.
copy_docs "$REPO_ROOT/packages/python/src/cachetta/docs"
