name: Python GitHub Release

on:
  push:
    tags:
      - 'py/cachetta-v*'

permissions:
  contents: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        working-directory: packages/python
        run: uv build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            packages/python/dist/cachetta-*.tar.gz
            packages/python/dist/cachetta-*.whl
