name: Python Release

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
        default: patch

jobs:
  release:
    uses: ./.github/workflows/py-publish.yaml
    with:
      bump_type: ${{ inputs.bump_type || 'patch' }}
    permissions:
      contents: write
      id-token: write
